"""add poll invitation to notification

Revision ID: 40f3e915d31b
Revises: 10cb2228de79
Create Date: 2026-05-29 11:20:06.754552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f3e915d31b'
down_revision = '10cb2228de79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_poll', 'hangout_polls', ['poll_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_poll', type_='foreignkey')
        batch_op.drop_column('poll_id')

    # ### end Alembic commands ###
