"""add poll_id to notifications

Revision ID: cbb574e36c51
Revises: 40f3e915d31b
Create Date: 2026-05-29 16:37:08.100924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb574e36c51'
down_revision = '40f3e915d31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notifications_poll_id_hangout_polls', 'hangout_polls', ['poll_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_poll_id_hangout_polls', type_='foreignkey')
        batch_op.drop_column('poll_id')

    # ### end Alembic commands ###
